### ISSUE TITLE
A, B, Full Term filter 

### ISSUE THREAD

**Issue by henrylyle** [uw-it-aca/retention-dashboard#140] opened 2021-06-24 17:15 UTC
The A, B, full term filter isn’t working as I’d expect it to. If I select A, I’d expect only A term students to show up, but A and A + B shows up. Same deal with B. 

![image](https://user-images.githubusercontent.com/58445569/123305535-13307f00-d4d5-11eb-83ed-0ec4217c529f.png)

**Comment by nick-falco** [comment] 2021-06-28 19:21
In the last team meeting we determined that the term filter is working as intended. The A Term, B Term and Full Term filters are checked independently and combined with OR logic.

For example,

If a user selects A Term and B Term, this implies that a row must contain at least A, or B, or both A and B, to be included in the filtered dataset.

**Closed by nick-falco** 2021-06-28 19:21 UTC
